### ISSUE TITLE
ERROR: manifest for xamanu/xmpp-turn:version-0.9 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by TheChiefMeat** [xamanu/xmpp-server#8]
Seems like the tagged image is no longer available

**Comment by xamanu** [comment]
Thanks for reporting! Indeed the build was failing, I released a version 10 and this has been successfully built an is available now: https://hub.docker.com/repository/docker/xamanu/xmpp-turn/tags?page=1&ordering=last_updated

**Comment by xamanu** [comment]
Closed after being solver and one month on inactivity
